options:
  # Don't merge default rules
  merge-default-rules: true

files:
  include:
    - 'css/*.css'

# Rule Configuration
rules:
  border-zero: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-css-comments: 0
  no-ids: 2
  no-important: 2
  no-color-literals: 0
  single-line-per-selector: 2
  pseudo-element: 2
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  hex-length:
    - 2
    - style: long
  nesting-depth:
    - 2
    - max-depth: 2
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 4
  shorthand-values:
    - 2
    - allowed-shorthands:
      - 1
      - 2
  quotes:
      - 2
      - style: single
  property-sort-order:
    - 2
    - order: recess
    - ignore-custom-properties: false
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
